version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: distsys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql:/sql
      - ./init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh
    ports:
      - "5433:5432"
