# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import customer_service_pb2 as customer__service__pb2


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBuyer = channel.unary_unary(
                '/customer.CustomerService/CreateBuyer',
                request_serializer=customer__service__pb2.CreateBuyerRequest.SerializeToString,
                response_deserializer=customer__service__pb2.CreateBuyerResponse.FromString,
                )
        self.ServerCreateBuyer = channel.unary_unary(
                '/customer.CustomerService/ServerCreateBuyer',
                request_serializer=customer__service__pb2.ServerCreateBuyerRequest.SerializeToString,
                response_deserializer=customer__service__pb2.ServerCreateBuyerResponse.FromString,
                )
        self.CreateCart = channel.unary_unary(
                '/customer.CustomerService/CreateCart',
                request_serializer=customer__service__pb2.CreateCartRequest.SerializeToString,
                response_deserializer=customer__service__pb2.CreateCartResponse.FromString,
                )
        self.ServerCreateCart = channel.unary_unary(
                '/customer.CustomerService/ServerCreateCart',
                request_serializer=customer__service__pb2.CreateCartRequest.SerializeToString,
                response_deserializer=customer__service__pb2.CreateCartResponse.FromString,
                )
        self.DeleteCartByBuyerId = channel.unary_unary(
                '/customer.CustomerService/DeleteCartByBuyerId',
                request_serializer=customer__service__pb2.DeleteCartByBuyerIdRequest.SerializeToString,
                response_deserializer=customer__service__pb2.DeleteCartByBuyerIdResponse.FromString,
                )
        self.ServerDeleteCartByBuyerId = channel.unary_unary(
                '/customer.CustomerService/ServerDeleteCartByBuyerId',
                request_serializer=customer__service__pb2.DeleteCartByBuyerIdRequest.SerializeToString,
                response_deserializer=customer__service__pb2.DeleteCartByBuyerIdResponse.FromString,
                )
        self.UpdateCartItemQuantity = channel.unary_unary(
                '/customer.CustomerService/UpdateCartItemQuantity',
                request_serializer=customer__service__pb2.UpdateCartItemQuantityRequest.SerializeToString,
                response_deserializer=customer__service__pb2.UpdateCartItemQuantityResponse.FromString,
                )
        self.ServerUpdateCartItemQuantity = channel.unary_unary(
                '/customer.CustomerService/ServerUpdateCartItemQuantity',
                request_serializer=customer__service__pb2.UpdateCartItemQuantityRequest.SerializeToString,
                response_deserializer=customer__service__pb2.UpdateCartItemQuantityResponse.FromString,
                )
        self.RemoveCartItem = channel.unary_unary(
                '/customer.CustomerService/RemoveCartItem',
                request_serializer=customer__service__pb2.RemoveCartItemRequest.SerializeToString,
                response_deserializer=customer__service__pb2.RemoveCartItemResponse.FromString,
                )
        self.ServerRemoveCartItem = channel.unary_unary(
                '/customer.CustomerService/ServerRemoveCartItem',
                request_serializer=customer__service__pb2.RemoveCartItemRequest.SerializeToString,
                response_deserializer=customer__service__pb2.RemoveCartItemResponse.FromString,
                )
        self.GetCartItem = channel.unary_unary(
                '/customer.CustomerService/GetCartItem',
                request_serializer=customer__service__pb2.GetCartItemRequest.SerializeToString,
                response_deserializer=customer__service__pb2.GetCartItemResponse.FromString,
                )
        self.GetBuyerCartItems = channel.unary_unary(
                '/customer.CustomerService/GetBuyerCartItems',
                request_serializer=customer__service__pb2.GetBuyerCartItemsRequest.SerializeToString,
                response_deserializer=customer__service__pb2.GetBuyerCartItemsResponse.FromString,
                )
        self.GetBuyerPurchase = channel.unary_unary(
                '/customer.CustomerService/GetBuyerPurchase',
                request_serializer=customer__service__pb2.GetBuyerPurchaseRequest.SerializeToString,
                response_deserializer=customer__service__pb2.GetBuyerPurchaseResponse.FromString,
                )
        self.GetBuyerId = channel.unary_unary(
                '/customer.CustomerService/GetBuyerId',
                request_serializer=customer__service__pb2.GetBuyerIdRequest.SerializeToString,
                response_deserializer=customer__service__pb2.GetBuyerIdResponse.FromString,
                )


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerCreateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerCreateCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCartByBuyerId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerDeleteCartByBuyerId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCartItemQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerUpdateCartItemQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveCartItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerRemoveCartItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCartItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerCartItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuyer,
                    request_deserializer=customer__service__pb2.CreateBuyerRequest.FromString,
                    response_serializer=customer__service__pb2.CreateBuyerResponse.SerializeToString,
            ),
            'ServerCreateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerCreateBuyer,
                    request_deserializer=customer__service__pb2.ServerCreateBuyerRequest.FromString,
                    response_serializer=customer__service__pb2.ServerCreateBuyerResponse.SerializeToString,
            ),
            'CreateCart': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCart,
                    request_deserializer=customer__service__pb2.CreateCartRequest.FromString,
                    response_serializer=customer__service__pb2.CreateCartResponse.SerializeToString,
            ),
            'ServerCreateCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerCreateCart,
                    request_deserializer=customer__service__pb2.CreateCartRequest.FromString,
                    response_serializer=customer__service__pb2.CreateCartResponse.SerializeToString,
            ),
            'DeleteCartByBuyerId': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCartByBuyerId,
                    request_deserializer=customer__service__pb2.DeleteCartByBuyerIdRequest.FromString,
                    response_serializer=customer__service__pb2.DeleteCartByBuyerIdResponse.SerializeToString,
            ),
            'ServerDeleteCartByBuyerId': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerDeleteCartByBuyerId,
                    request_deserializer=customer__service__pb2.DeleteCartByBuyerIdRequest.FromString,
                    response_serializer=customer__service__pb2.DeleteCartByBuyerIdResponse.SerializeToString,
            ),
            'UpdateCartItemQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCartItemQuantity,
                    request_deserializer=customer__service__pb2.UpdateCartItemQuantityRequest.FromString,
                    response_serializer=customer__service__pb2.UpdateCartItemQuantityResponse.SerializeToString,
            ),
            'ServerUpdateCartItemQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerUpdateCartItemQuantity,
                    request_deserializer=customer__service__pb2.UpdateCartItemQuantityRequest.FromString,
                    response_serializer=customer__service__pb2.UpdateCartItemQuantityResponse.SerializeToString,
            ),
            'RemoveCartItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveCartItem,
                    request_deserializer=customer__service__pb2.RemoveCartItemRequest.FromString,
                    response_serializer=customer__service__pb2.RemoveCartItemResponse.SerializeToString,
            ),
            'ServerRemoveCartItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerRemoveCartItem,
                    request_deserializer=customer__service__pb2.RemoveCartItemRequest.FromString,
                    response_serializer=customer__service__pb2.RemoveCartItemResponse.SerializeToString,
            ),
            'GetCartItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCartItem,
                    request_deserializer=customer__service__pb2.GetCartItemRequest.FromString,
                    response_serializer=customer__service__pb2.GetCartItemResponse.SerializeToString,
            ),
            'GetBuyerCartItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerCartItems,
                    request_deserializer=customer__service__pb2.GetBuyerCartItemsRequest.FromString,
                    response_serializer=customer__service__pb2.GetBuyerCartItemsResponse.SerializeToString,
            ),
            'GetBuyerPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchase,
                    request_deserializer=customer__service__pb2.GetBuyerPurchaseRequest.FromString,
                    response_serializer=customer__service__pb2.GetBuyerPurchaseResponse.SerializeToString,
            ),
            'GetBuyerId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerId,
                    request_deserializer=customer__service__pb2.GetBuyerIdRequest.FromString,
                    response_serializer=customer__service__pb2.GetBuyerIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customer.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/CreateBuyer',
            customer__service__pb2.CreateBuyerRequest.SerializeToString,
            customer__service__pb2.CreateBuyerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerCreateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/ServerCreateBuyer',
            customer__service__pb2.ServerCreateBuyerRequest.SerializeToString,
            customer__service__pb2.ServerCreateBuyerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/CreateCart',
            customer__service__pb2.CreateCartRequest.SerializeToString,
            customer__service__pb2.CreateCartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerCreateCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/ServerCreateCart',
            customer__service__pb2.CreateCartRequest.SerializeToString,
            customer__service__pb2.CreateCartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCartByBuyerId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/DeleteCartByBuyerId',
            customer__service__pb2.DeleteCartByBuyerIdRequest.SerializeToString,
            customer__service__pb2.DeleteCartByBuyerIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerDeleteCartByBuyerId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/ServerDeleteCartByBuyerId',
            customer__service__pb2.DeleteCartByBuyerIdRequest.SerializeToString,
            customer__service__pb2.DeleteCartByBuyerIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCartItemQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/UpdateCartItemQuantity',
            customer__service__pb2.UpdateCartItemQuantityRequest.SerializeToString,
            customer__service__pb2.UpdateCartItemQuantityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerUpdateCartItemQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/ServerUpdateCartItemQuantity',
            customer__service__pb2.UpdateCartItemQuantityRequest.SerializeToString,
            customer__service__pb2.UpdateCartItemQuantityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveCartItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/RemoveCartItem',
            customer__service__pb2.RemoveCartItemRequest.SerializeToString,
            customer__service__pb2.RemoveCartItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerRemoveCartItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/ServerRemoveCartItem',
            customer__service__pb2.RemoveCartItemRequest.SerializeToString,
            customer__service__pb2.RemoveCartItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCartItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/GetCartItem',
            customer__service__pb2.GetCartItemRequest.SerializeToString,
            customer__service__pb2.GetCartItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBuyerCartItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/GetBuyerCartItems',
            customer__service__pb2.GetBuyerCartItemsRequest.SerializeToString,
            customer__service__pb2.GetBuyerCartItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBuyerPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/GetBuyerPurchase',
            customer__service__pb2.GetBuyerPurchaseRequest.SerializeToString,
            customer__service__pb2.GetBuyerPurchaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBuyerId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/GetBuyerId',
            customer__service__pb2.GetBuyerIdRequest.SerializeToString,
            customer__service__pb2.GetBuyerIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
